-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.clientes
(
    id_cliente serial NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default",
    telefone character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT clientes_pkey PRIMARY KEY (id_cliente),
    CONSTRAINT clientes_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.produtos
(
    id_produto serial NOT NULL,
    nome_produto character varying(100) COLLATE pg_catalog."default" NOT NULL,
    preco numeric(10, 2) NOT NULL,
    CONSTRAINT produtos_pkey PRIMARY KEY (id_produto)
);

CREATE TABLE IF NOT EXISTS public.vendas
(
    id_venda serial NOT NULL,
    id_cliente integer,
    id_produto integer,
    data_venda date DEFAULT CURRENT_DATE,
    CONSTRAINT vendas_pkey PRIMARY KEY (id_venda)
);

ALTER TABLE IF EXISTS public.vendas
    ADD CONSTRAINT vendas_id_cliente_fkey FOREIGN KEY (id_cliente)
    REFERENCES public.clientes (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vendas
    ADD CONSTRAINT vendas_id_produto_fkey FOREIGN KEY (id_produto)
    REFERENCES public.produtos (id_produto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;